name: Code linting

on:
  push:
    paths:
      - '**.py'
  pull_request:
    paths:
      - '**.py'
  workflow_dispatch:

jobs:
  linter:
    name: Lint code
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
          cache: pip
          cache-dependency-path: '.github/**/*requirements.txt'

      - name: Install dependencies
        run: |
          pip install -U -r ".github/requirements.txt"
          pip install -U pyupgrade

      - name: Lint with flake8
        run: flake8 --show-source --statistics

      - name: Check code with pyupgrade
        run: |
          find . -type f -name "*.py" -exec pyupgrade --py38-plus {} \;
          test $(git status --porcelain | wc -l) = 0
